name: Bats-Tests

on: [push, pull_request, workflow_dispatch]

jobs:

  bats-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        shell: 'script -q -e -c "bash {0}"' # work around tty issues
        run: |
          git_workflow=$GITHUB_WORKFLOW
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          git_branch=${GITHUB_REF#refs/heads/}
          \
          raw_tag="$git_workflow/$git_branch/$git_hash"
          lowercase_tag=$raw_tag | tr [:upper:] [:lower:]
          dockerfile="/home/runner/work/DevSecOps/DevSecOps/bats.github.Dockerfile"
          \
          volumn_loc="~/git/DevSecOps"
          mount_loc=""
          \
          docker build -v "$volumn_loc:/root/git/DevSecOps" --tag "$lowercase_tag" -f $dockerfile .
          docker run -it "$lowercase_tag" --version